export {default as Navbar} from './Navbar/Navbar'
export {default as Intro} from './intro/Intro'
export {default as About} from './about/About'
export {default as News} from './news/News'
export {default as Footer} from './footer/Footer'