service: citi-aether-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-1

functions:
  connect:
    handler: connect/app.handler
    events:
      - http: ANY connect
      - http: "ANY {proxy+}"
  payments:
    handler: payments/app.handler
    events:
      - http: ANY payments
      - http: "ANY {proxy+}"

resources:
  Resources:
    CitiAetherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CitiUsers
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST