service: citi-aether-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-1

functions:
  base:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true

resources:
  Resources:
    CitiAetherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CitiUsers
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
